---
name: 'Setup Apache Spark'
description: 'Set up Apache Spark and add the command-line tools to the PATH.'
author: 'vemonet'
inputs:
  spark-version:
    description: "Apache Spark version to install, see https://spark.apache.org/downloads.html"
    default: '3.0.2'
    required: false
  hadoop-version:
    description: "Hadoop version"
    default: '3.2'
    required: false
  py4j-version:
    description: "Py4J version."
    default: '0.10.9'
    required: false
outputs:
  spark-version:
    description: "The installed Apache Spark version."
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'star'
  color: 'orange'
