name: 🐞 Bug Report
title: '🐞 '
description: Report a bug to help us improve
labels: ['type: bug']
assignees: ['vemonet']

body:
  - type: markdown
    attributes:
      value: |
        Please search for [existing issues](https://github.com/vemonet/setup-spark/issues?q=is%3Aissue) about this problem first.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What are you trying to get done, what has happened, what went wrong, and what did you expect?
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a workflow run where the bug happened, or repo to reproduce the behaviour.
      placeholder: |
        Workflow run URL, repository URL...

  - type: input
    id: action-version
    attributes:
      label: Which version of the action are you using?
      placeholder: |
        `v1`, `main`, other tag?
    validations:
      required: true

  - type: input
    id: spark-version
    attributes:
      label: With which versions of Spark is it happening?
      placeholder: |
        3.4.1, 3.1.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System and environment
      description: GitHub-hosted, Self-hosted? ubuntu-latest, macos-latest?
      placeholder: |
        GitHub-hosted with ubuntu-latest
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
