name: Run setup-spark action
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-setup-spark:
    name: Test Setup Spark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version: [3.0.2, 3.1.1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: npm install

    # - name: Lint
    #   run: npm run format-check
    # - name: npm test
    #   run: npm test

    - name: Run setup-spark ${{ matrix.spark-version }}
      uses: ./
      with:
        spark-version: ${{ matrix.spark-version }}
        hadoop-version: 3.2

    - name: Check Spark
      run: spark-submit --version
