name: Test setup-spark action
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:

  test-setup-spark:
    name: ✅ Test setup Spark
    runs-on: ${{ matrix.versions.os }}
    strategy:
      matrix:
        versions:
          - os: 'ubuntu-latest'
            spark: 3.4.1
            hadoop: 3
          - os: 'ubuntu-latest'
            spark: 3.3.2
            hadoop: 3
          - os: 'ubuntu-latest'
            spark: 3.0.2
            hadoop: 3.2
          - os: 'ubuntu-latest'
            spark: 3.1.2
            hadoop: 3.2
          - os: 'macos-latest'
            spark: 3.4.1
            hadoop: 3

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: npm install
      run: npm install

    # - name: Lint
    #   run: npm run lint

    - name: Run setup-spark ${{ matrix.versions.spark }}
      uses: ./
      with:
        spark-version: ${{ matrix.versions.spark }}
        hadoop-version: ${{ matrix.versions.hadoop }}
        # spark-url: 'https://archive.apache.org/dist/spark/spark-${{ matrix.spark-version }}/spark-${{ matrix.spark-version }}-bin-hadoop3.2.tgz'

    - name: Check Spark
      run: |
        spark-submit --version
        echo $SPARK_HOME



  test-setup-scala-version:
    name: 🛢️ Test setup with specific Scala version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - spark: 3.2.1
            hadoop: 3.2
            scala: 2.13
          # - spark: 3.4.1
          #   hadoop: 3
          #   scala: 2.12

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: npm install
      run: npm install

    - name: Run setup-spark ${{ matrix.versions.spark }}
      uses: ./
      with:
        spark-version: ${{ matrix.versions.spark }}
        hadoop-version: ${{ matrix.versions.hadoop }}
        scala-version: ${{ matrix.versions.scala }}
        # spark-url: 'https://archive.apache.org/dist/spark/spark-${{ matrix.spark-version }}/spark-${{ matrix.spark-version }}-bin-hadoop3.2.tgz'

    - name: Check Spark
      run: spark-submit --version



  CodeQL-analysis:
    name: 🔎 CodeQL analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2


  check-license:
    name: 📜 Check licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Install licensed
        run: |
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/releases/download/3.1.0/licensed-3.1.0-linux-x64.tar.gz
          tar -xzf licensed.tar.gz
      - run: ./licensed status